apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hcd-jupyterlab
  namespace: test
  labels:
    app: jupyterlab
spec:
  serviceName: jupyterlab
  replicas: 1
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      containers:
      - name: jupyterlab
        image: harbor-standard.kuberix.co.kr/library/hcd-jupyterlab:cpu-v3.4.2-v0.6.21
        command: ["/bin/bash", "-c"]
        args: ["start.sh jupyter lab --ip=0.0.0.0 --allow-root --LabApp.token=''"]
        #args: ["start.sh jupyter lab --LabApp.token=''"]
        ports:
        - containerPort: 8888
          name: jupyter
        env:
        - name: TZ
          value: "Asia/Seoul"  # 타임존 설정
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-service
  namespace: test
  labels:
    app: jupyterlab
spec:
  type: ClusterIP
  ports:
    - port: 8888  # JupyterLab의 기본 포트
      targetPort: 8888
  selector:
    app: jupyterlab

